NEI<-readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
NEISCC <- merge(NEI, SCC, by="SCC")
NEISCCWithCoal<-grepl("coal", NEISCC$Short.Name, ignore.case=TRUE)
CoalCombustNEI<-subset(NEISCC,NEISCCWithCoal)
EmissionByYear<-aggregate(Emissions~year,CoalCombustNEI,sum)
png("Plot4.png")
barplot(EmissionByYear$Emissions,names.arg=EmissionByYear$year,main="Coal Combustion Related Emission By Year",xlab="Year",ylab="PM2.5*Emissions")
dev.off()
